### PR TITLE
Colorado exemption calculator

### PR DESCRIPTION
**Pull request by lcontreras21**
[Monday Ticket](https://clearlyenergy-inc.monday.com/boards/5735334679/pulses/6145748645

#### Changes
Reformatted the validate.js file to stop the linter from screaming.

Colorado Requested some form validation on their Exemption form. This PR adds in a new field called 'key_value' that displays a choice field with an input box. The user can delete specific rows ('pairs') and add as they please. For the CO Form specifically, there is some validation for what can go in there but otherwise it'll just succeed'.  

This new 'key_value' field can be added just like any other field. 

Ex:
image

#### On Prod
On the exemption form, the 'calculator' field needs to be changed to have the 'key_value' data type, all of the Property Type options in the 'propertytype' field need to be copied over, and the include blank option needs to be checked. 

#### TODO:
* I have not tested what happens when there's multiple key_value fields
* I have not modified the get_building_data function in staff.py to conform with this new field
* It is currently not working with the EditTicketForm
    *  Since it's working fine with the normal TicketForm, I'm not that pressed to work on this item till next week

#### Thanks
Thanks, Itai, for doing a lot of the work with the Queue editor and MutliValueField. That really cut down on me having to dig through the documentation to come up with this frankenstein.

### CODE REVIEW

**Comment by SWGHarris** [comment]
Where am I able to find the exemption form?

**Comment by lcontreras21** [comment]
https://co.beam-portal.org/helpdesk/tickets/submit/16/?org=Building%20Performance%20Colorado

I tried to find a way to get the SQL commands to run for testing but that seemed really tedious after a quick google. 

To get the same functionality locally to test the functionality though, in a local form, add two fields called 'reason' and 'calculator'. Copy over the other field information from the [admin page](https://co.beam-portal.org/admin/helpdesk/customfield/?ticket_form__id__exact=16). But a higher priority would be simply to checkout the key_value field and that you don't need the CO form.

I just wanted a second set of eyes on this since since it's so rushed and I haven't worked in helpdesk in probably over a year or year and a half. Make sure I don't step on any helpdesk toes

**Comment by ebeers-png** [comment]
I can take a look at it tomorrow morning if that's alright!

**Comment by ebeers-png** [comment]
Ok, my quick notes:

- The form doesn't work with more than one key_value field; looks like it's because `const pairs` gets redefined in the Javascript?
- If I add a new row with "+ Add", I can click X to delete that new row, but not any of the others
- On the ticket details page, the key_value field displays the results as a Python list. Maybe clean it up into a basic list (like `['Key One': 'Value', 'Key Two': 'Value']` -> `Key One: Value, Key Two: Value`), at least for the public ticket?
image



Other things that can probably be fixed later:
- Users can select the same key multiple times, and that works fine, but should we enforce key uniqueness in the future?
- In the form settings page (where forms can be created/edited within Helpdesk), selecting the data type Key Value should cause the List Values field to appear (like what happens when the List data type is selected).

**Comment by lcontreras21** [comment]
With the latest commit, it should address all of your notes on top of making things a bit more robust. 

Thanks for all the feedback!!

**Pull request merged**
